1) Combining a one and a two-dimensional NumPy Array 2) Flatten a 2d numpy array into 1d array 3) Reverse a numpy array 4) Practice operations like Get the maximum value from given array Get the minimum value from given array Find the number of rows and columns of a given array using NumPy Select the elements from a given array (each element and specific element) Find the sum of values in a 2D array using for loop Adding, Subtracting, multiplying, dividing arrays in Numpy 5) Iterate 3D array using for loop and nditer 6) Study the following program import numpy as np # create a numpy 1d-arrays arr1 = np.array([3, 4]) arr2 = np.array([1, 0]) # find average of NumPy arrays avg = (arr1 + arr2) / 2 print("Average of NumPy arrays:\n", avg) -> Calculate average mean median mode values of two NumPy 2d-arrays



In [ ]:
#1) Combining a one and a two-dimensional NumPy Array
import pandas as pd
import numpy as np
arr1=([22,44,33,11])
arr2= ([
    [23,54,5,32],
    [99,1,23,77]
])
print(arr1+arr2)


[22, 44, 33, 11, [23, 54, 5, 32], [99, 1, 23, 77]]
[[23, 54, 5, 32], [99, 1, 23, 77]]


In [ ]:
#2) Flatten a 2d numpy array into 1d array

arr2= np.array([
    [23,54,5,32],
    [99,1,23,77]
])
print(arr2.reshape(8,))

[23 54  5 32 99  1 23 77]


In [ ]:
#3) Reverse a numpy array
arr= ([33,12,80,67,55])
print(arr[::-1])

[55, 67, 80, 12, 33]


In [30]:
#4) Practice operations like Get the maximum value from given array
# Get the minimum value from given array Find the number of rows and columns of a given array
# using NumPy Select the elements from a given array (each element and specific element)
# Find the sum of values in a 2D array using for loop
# Adding, Subtracting, multiplying, dividing arrays in Numpy
arr=np.array([22, 54, 21, 78, 55, 11, 90, 34])
print(arr.max())
print(arr.min())
print(arr.size)
print(arr.shape)
print(arr[4])
arr1= np.array([
    [22,56, 87, 43, 41],
    [22, 90, 11, 23, 65]
])
for i in arr1:
    a= sum(i)
    print(a,a.dtype)

arr2= np.array([3,4,2,5])
arr3= np.array([6,3,2,0])
arr4= np.array([
    [3,4,5,6],
    [1,6,2,0]
]
)
res1= arr4 + arr3
print(res1)
res2= arr3 - arr2
print(res2)
res4= arr2 * arr4
print(res4)
res5= arr3 / arr2
print(res5)




90
11
8
(8,)
55
249 int64
211 int64
[[9 7 7 6]
 [7 9 4 0]]
[ 3 -1  0 -5]
[[ 9 16 10 30]
 [ 3 24  4  0]]
[2.   0.75 1.   0.  ]


In [42]:
#5) Iterate 3D array using for loop and nditer
arr= np.array(
    [[
    [2,3,4],
    [6,5,4]],
    [
        [99,3,1],
        [0,33,1]
     ]])
print(arr)
print(arr[0,1,1])

[[[ 2  3  4]
  [ 6  5  4]]

 [[99  3  1]
  [ 0 33  1]]]
5


In [43]:
#6) Study the following program import numpy as np # create a numpy 1d-arrays
# arr1 = np.array([3, 4]) arr2 = np.array([1, 0]) # find average of NumPy arrays
# avg = (arr1 + arr2) / 2 print("Average of NumPy arrays:\n", avg) ->
# Calculate average mean median mode values of two NumPy 2d-arrays
a9 = np.array([[31,22,44,94,25], [27,99,62,13,54], [51,63,15,47,18]])
a10 = np.array([[30,92,38,94,25], [27,45,37,80,36], [60,63,64,47,80]])

print(f"Array 1: {a9}")
print("___________________________")
print(f"Array 1: {a10}")
print("___________________________")
a11 = np.concatenate((a9.flatten(), a10.flatten()))
print(f"Combined Array: {a11}")
a12 = np.sort(a11)
print(f"Combined & Sorted Array: {a12}")
mean = np.mean(a11)
median = np.median(a11)
values, counts = np.unique(a11, return_counts=True)
mode = values[np.argmax(counts)]

print("Mean:", mean.round(2))
print("Median:", median)
print("Mode:", mode)


Array 1: [[31 22 44 94 25]
 [27 99 62 13 54]
 [51 63 15 47 18]]
___________________________
Array 1: [[30 92 38 94 25]
 [27 45 37 80 36]
 [60 63 64 47 80]]
___________________________
Combined Array: [31 22 44 94 25 27 99 62 13 54 51 63 15 47 18 30 92 38 94 25 27 45 37 80
 36 60 63 64 47 80]
Combined & Sorted Array: [13 15 18 22 25 25 27 27 30 31 36 37 38 44 45 47 47 51 54 60 62 63 63 64
 80 80 92 94 94 99]
Mean: 49.43
Median: 46.0
Mode: 25
